version: '3.8'

services:
  server:
    build: server/
    ports:
      - "80:80"
    volumes:
      - ./server:/var/www/html
  db:
    build: db/
    ports:
        - "3308:3308"
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      